export const SEARCH = "SEARCH";
export const SEARCHB = "SEARCHB";

export const POST_PRODUCT = "POSTPRUDOCT";
export const PRODUCT_DETAIL = "PRODUCTDETAIL";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PRODUCTBYCATEGORIES = "GET_PRODUCTBYCATEGORIES";
